/**
 * DemoScript Builder utilities
 * Types and functions for the visual demo builder
 */

/**
 * A step in the demo builder
 */
export interface BuilderStep {
  id: string;
  method: string;
  endpoint: string;
  title: string;
  body?: unknown;
  headers?: Record<string, string>;
  save?: Record<string, string>;  // varName -> jsonPath
}

/**
 * Builder state
 */
export interface BuilderState {
  mode: 'openapi' | 'custom';
  baseUrl: string;
  openapiUrl?: string;
  steps: BuilderStep[];
  variables: Record<string, unknown>;
}

/**
 * Demo settings for YAML generation
 */
export interface DemoSettings {
  title?: string;
  description?: string;
  author?: string;
}

/**
 * Escape a string value for YAML
 */
function yamlEscape(value: string): string {
  // If the string contains special characters or starts with special chars, quote it
  if (
    value.includes(':') ||
    value.includes('#') ||
    value.includes('\n') ||
    value.includes('"') ||
    value.startsWith(' ') ||
    value.endsWith(' ') ||
    value.startsWith('{') ||
    value.startsWith('[') ||
    /^[0-9]/.test(value) ||
    value === 'true' ||
    value === 'false' ||
    value === 'null' ||
    value === ''
  ) {
    // Use double quotes and escape internal quotes
    return `"${value.replace(/"/g, '\\"')}"`;
  }
  return value;
}

/**
 * Convert a value to YAML format
 */
function toYamlValue(value: unknown, indent: number = 0): string {
  if (value === null || value === undefined) {
    return 'null';
  }

  if (typeof value === 'string') {
    return yamlEscape(value);
  }

  if (typeof value === 'number' || typeof value === 'boolean') {
    return String(value);
  }

  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    const spaces = ' '.repeat(indent);
    return '\n' + value.map(v => `${spaces}- ${toYamlValue(v, indent + 2)}`).join('\n');
  }

  if (typeof value === 'object') {
    const entries = Object.entries(value);
    if (entries.length === 0) return '{}';
    const spaces = ' '.repeat(indent);
    return '\n' + entries.map(([k, v]) => {
      const yamlVal = toYamlValue(v, indent + 2);
      // If the value starts with newline, don't add space after colon
      if (yamlVal.startsWith('\n')) {
        return `${spaces}${k}:${yamlVal}`;
      }
      return `${spaces}${k}: ${yamlVal}`;
    }).join('\n');
  }

  return String(value);
}

/**
 * Convert a BuilderStep to YAML object format
 */
export function stepToYaml(step: BuilderStep): string[] {
  const lines: string[] = [];

  // REST step declaration
  lines.push(`  - rest: ${step.method} ${step.endpoint}`);
  lines.push(`    title: ${yamlEscape(step.title)}`);

  // Headers
  if (step.headers && Object.keys(step.headers).length > 0) {
    lines.push('    headers:');
    for (const [key, value] of Object.entries(step.headers)) {
      lines.push(`      ${key}: ${yamlEscape(value)}`);
    }
  }

  // Body as defaults
  if (step.body && typeof step.body === 'object') {
    const entries = Object.entries(step.body as Record<string, unknown>);
    if (entries.length > 0) {
      lines.push('    defaults:');
      for (const [key, value] of entries) {
        const yamlVal = toYamlValue(value, 6);
        if (yamlVal.startsWith('\n')) {
          lines.push(`      ${key}:${yamlVal}`);
        } else {
          lines.push(`      ${key}: ${yamlVal}`);
        }
      }
    }
  }

  // Save variables
  if (step.save && Object.keys(step.save).length > 0) {
    lines.push('    save:');
    for (const [varName, jsonPath] of Object.entries(step.save)) {
      lines.push(`      ${varName}: ${jsonPath}`);
    }
  }

  return lines;
}

/**
 * Generate a complete demo YAML from builder state
 */
export function generateDemoYaml(state: BuilderState, settings?: DemoSettings): string {
  const lines: string[] = [];

  // Header
  lines.push(`title: ${yamlEscape(settings?.title || 'My Demo')}`);
  lines.push(`description: ${yamlEscape(settings?.description || 'Generated by DemoScript Builder')}`);

  if (settings?.author) {
    lines.push(`author: ${yamlEscape(settings.author)}`);
  }

  lines.push('');

  // Settings
  if (state.baseUrl || state.openapiUrl) {
    lines.push('settings:');
    if (state.baseUrl) {
      lines.push(`  base_url: ${yamlEscape(state.baseUrl)}`);
    }
    if (state.openapiUrl) {
      lines.push(`  openapi: ${yamlEscape(state.openapiUrl)}`);
    }
    lines.push('');
  }

  // Steps
  if (state.steps.length > 0) {
    lines.push('steps:');
    for (const step of state.steps) {
      lines.push(...stepToYaml(step));
      lines.push('');
    }
  }

  return lines.join('\n');
}

/**
 * Parse a YAML demo file into BuilderState (basic parsing)
 * Note: This is a simplified parser for basic import functionality
 */
export function parseYamlToBuilderState(_yaml: string): Partial<BuilderState> {
  // This would require a proper YAML parser
  // For now, return empty state - can be implemented with js-yaml if needed
  return {
    steps: [],
    variables: {},
  };
}
